#!/usr/bin/env bash
# Installs Nginx with the following requirements:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
